modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="GoldenEye70, quilt-lead"

description='''
Creosote compatibility recipes for Minecraft 1.21.1 NeoForge.

Originally created by GoldenEye70 as CreosotePatch.
This NeoForge continuation is maintained by quilt-lead.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
